services:
  - name: legallens-frontend
    type: static
    buildCommand: npm run render-build
    publishDir: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://legallens-backend.onrender.com

  - name: legallens-backend
    type: web
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://legallens-frontend.onrender.com
      - key: SESSION_SECRET
        value: legallens-session-secret-2024-xyz789 